CREATE TABLE IF NOT EXISTS NEWS_ARTICLE_ANALYSIS (
    ANALYSIS_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    COMPANY_QUERY VARCHAR(255) NOT NULL,
    ARTICLE_HASH CHAR(64) NOT NULL,
    TITLE TEXT NOT NULL,
    DESCRIPTION TEXT NULL,
    NAVER_LINK VARCHAR(2048) NULL,
    ORIGINAL_LINK VARCHAR(2048) NULL,
    PUBLISHED_AT DATETIME NULL,
    SENTIMENT VARCHAR(16) NOT NULL,
    CONFIDENCE DECIMAL(6, 5) NOT NULL,
    FIRST_COLLECTED_AT DATETIME NOT NULL,
    LAST_ANALYZED_AT DATETIME NOT NULL,
    PRIMARY KEY (ANALYSIS_ID),
    UNIQUE KEY UX_NEWS_ARTICLE_ANALYSIS_QUERY_HASH (COMPANY_QUERY, ARTICLE_HASH),
    KEY IX_NEWS_ARTICLE_ANALYSIS_QUERY_PUBLISHED (COMPANY_QUERY, PUBLISHED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
