-- 알림 기능 전용 테이블
-- 기존 USER / COMPANY 테이블에 외래키를 걸지 않아 로그인·회원가입에 영향을 주지 않습니다.

CREATE TABLE IF NOT EXISTS COMPANY_ANALYSIS_SNAPSHOT (
  SNAPSHOT_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT UNSIGNED NOT NULL,
  COMPANY_ID BIGINT UNSIGNED NOT NULL,
  RISK_SIGNAL_RATE DECIMAL(5,2) NOT NULL,
  ANALYZED_COUNT INT UNSIGNED NOT NULL DEFAULT 0,
  ANALYZED_AT DATETIME NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (SNAPSHOT_ID),
  KEY IX_SNAPSHOT_USER_COMPANY_TIME (USER_ID, COMPANY_ID, ANALYZED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS COMPANY_ALERT (
  ALERT_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT UNSIGNED NOT NULL,
  COMPANY_ID BIGINT UNSIGNED NOT NULL,
  ALERT_TYPE VARCHAR(30) NOT NULL,
  PREVIOUS_RATE DECIMAL(5,2) NULL,
  CURRENT_RATE DECIMAL(5,2) NOT NULL,
  CHANGE_RATE DECIMAL(5,2) NULL,
  DETECTED_AT DATETIME NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (ALERT_ID),
  KEY IX_ALERT_USER_TYPE_TIME (USER_ID, ALERT_TYPE, DETECTED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;