-- 로그인 사용자별 AI 대응자료 생성 이력 저장 테이블
CREATE TABLE IF NOT EXISTS RESPONSE_DRAFT_HISTORY (
  DRAFT_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT UNSIGNED NOT NULL,

  ISSUE_NAME VARCHAR(255) NOT NULL,
  INDUSTRY VARCHAR(100) NOT NULL,
  DOCUMENT_TYPE VARCHAR(50) NOT NULL,

  -- 생성에 사용한 이슈 분석 내용과 추가 요청
  ANALYSIS_TEXT TEXT NOT NULL,
  ADDITIONAL_REQUEST TEXT NULL,

  -- AI가 생성한 최종 초안
  DRAFT_RESPONSE LONGTEXT NOT NULL,
  RISK_TYPE VARCHAR(50) NULL,
  GENERATION_STATUS VARCHAR(30) NOT NULL DEFAULT 'generated',

  -- 생성 근거로 사용한 기사 최대 3건
  REFERENCE_ARTICLES JSON NULL,
  GENERATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (DRAFT_ID),
  KEY IX_RESPONSE_DRAFT_HISTORY_USER_TIME (USER_ID, GENERATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
