CREATE TABLE IF NOT EXISTS USER_SAVED_CASE (
    SAVED_CASE_ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    CASE_KEY VARCHAR(255) NOT NULL,
    CASE_ID BIGINT NULL,

    CASE_TITLE VARCHAR(200) NOT NULL,
    COMPANY_NAME VARCHAR(100) NULL,
    INDUSTRY VARCHAR(100) NULL,
    RISK_TYPE VARCHAR(50) NULL,
    START_DATE DATE NULL,
    DURATION_DAYS INT NULL,
    ARTICLE_COUNT INT NULL,

    REPRESENTATIVE_NEWS_ID BIGINT NULL,
    REPRESENTATIVE_TITLE VARCHAR(500) NULL,
    REPRESENTATIVE_URL VARCHAR(2048) NULL,
    AI_SUMMARY_JSON JSON NOT NULL,

    SAVED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (SAVED_CASE_ID),
    UNIQUE KEY UK_USER_SAVED_CASE_USER_KEY (USER_ID, CASE_KEY),
    KEY IX_USER_SAVED_CASE_USER_TIME (USER_ID, SAVED_AT),
    KEY IX_USER_SAVED_CASE_CASE_ID (CASE_ID),
    CONSTRAINT FK_USER_SAVED_CASE_USER
        FOREIGN KEY (USER_ID) REFERENCES `USER` (USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_USER_SAVED_CASE_CASE
        FOREIGN KEY (CASE_ID) REFERENCES CRISIS_CASE (CASE_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
