export const ROUTES = {
  HOME: "/",
  COMPANY_ANALYSIS: "/company-analysis",
  COMPANY_DETAIL: "/company-analysis/company",
  COMPANY_WATCHLIST: "/company-analysis/watchlist",
  RESPONSE_CENTER: "/response-center",
  CASE_SIMULATOR: "/response-center/case-simulator",
  RESPONSE_GENERATOR: "/response-center/response-generator",
  ALERTS: "/alerts",
  RISK_ALERT: "/alerts/risk-alert",
  MAJOR_ISSUE_ALERT: "/alerts/major-issue",
  COMPANY_SEARCH: "/company-analysis/search",
  STOCK_SEARCH: "/stock-search",
  COMUNITY: "/comunity",
  COMMUNITY_STOCK: "/comunity/stock",
  COMMUNITY_NEWS: "/comunity/news",
  COMMUNITY_COMPANY_HUB: "/comunity/company-hub",
  LOGIN: "/login",
  SIGNUP: "/signup",
  MYPAGE: "/mypage",
};
