export const ROUTES = {
  HOME: "/",
  DASHBOARD: "/dashboard",
  DASHBOARD_WATCHLIST: "/dashboard/watchlist",
  DASHBOARD_ISSUE_RISK: "/dashboard/issue-risk",
  COMPANY_ANALYSIS: "/company-analysis",
  COMPANY_DETAIL: "/company-analysis/company",
  COMPANY_WATCHLIST: "/company-analysis/watchlist",
  RESPONSE_CENTER: "/response-center",
  CASE_SIMULATOR: "/response-center/case-simulator",
  RESPONSE_GENERATOR: "/response-center/response-generator",
  ALERTS: "/alerts",
  COMPANY_SEARCH: "/company-analysis/search",
  LOGIN: "/login",
  SIGNUP: "/signup",
};
